### ISSUE TITLE
Msg dependencies redirection

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_android#6]
Before releasing the follower, panorama apps, redirect dependencies to turtlebot_msgs and then delete the msg/srvs in turtlebot_follower and turtlebot_panorama.

**Comment by corot** [comment]
This commit do the job on turtlebot_apps side:
https://github.com/turtlebot/turtlebot_apps/commit/039faa2407a9fd94b3d1e59707e955e6a9039145
