### ISSUE TITLE
Map navigation crashes when it reads a big map

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot_android#8]
For example, Willow maps.

OccupancyGridLayer, lines 104 and 105 it check for a maximum size of 1024x1024 with Preconditions.checkArgument, what throws an exception if the map is bigger.

Provide instead a polite message and ask to choose another map. Also, the hardcoded 1024 should be a parameter.

**Comment by bit-pirate** [comment]
Please add details about your devices, too.

**Comment by corot** [comment]
Why I opened this here? Should be in https://github.com/rosjava/android_apps.
Moving....
